### ISSUE TITLE
Support for EMBEDDED

### ISSUE THREAD

**Issue by krunarsson** [orientechnologies/spark-orientdb#12]
Is it possible to add support for EMBEDDED type? 

I am trying to query orient db vertex with few fields of EMBEDDED type and I am getting the following exception. 

```
Exception in thread "main" scala.MatchError: EMBEDDED (of class com.orientechnologies.orient.core.metadata.schema.OType)
	at org.apache.spark.orientdb.graphs.OrientDBGraphWrapper.getCatalystType(OrientDBGraphWrapper.scala:39)
	at org.apache.spark.orientdb.graphs.OrientDBGraphVertexWrapper.resolveTable(OrientDBGraphWrapper.scala:239)
	at org.apache.spark.orientdb.graphs.OrientDBVertexRelation$$anonfun$schema$1.apply(OrientDBRelation.scala:31)
	at org.apache.spark.orientdb.graphs.OrientDBVertexRelation$$anonfun$schema$1.apply(OrientDBRelation.scala:26)
	at scala.Option.getOrElse(Option.scala:121)...
```

**Comment by krunarsson** [comment]
There is no issue with this, I forgot to include the schema for the query. This issue should be ignored.
