### ISSUE TITLE
Error on handling 'in' and 'out' properties on edges.

### ISSUE THREAD

**Issue by Dollyn** [orientechnologies/spark-orientdb#15]
When creating edge class, if you specify the 'from vertex' or 'to vertex' class type:
![image](https://user-images.githubusercontent.com/184413/36715519-89284e92-1bd1-11e8-9b8b-7545ef4310d3.png)
Orientdb will create a 'in' property and a 'out' property with type 'LINK': 
![image](https://user-images.githubusercontent.com/184413/36715842-ebe97118-1bd2-11e8-9eff-4dd22f1ec083.png)

OrientDBGraphEdgeWrapper can't handle these properties properly:

Exception in thread "main" scala.MatchError: LINK (of class com.orientechnologies.orient.core.metadata.schema.OType)
	at org.apache.spark.orientdb.graphs.OrientDBGraphWrapper.getCatalystType(OrientDBGraphWrapper.scala:39)
	at org.apache.spark.orientdb.graphs.OrientDBGraphEdgeWrapper.resolveTable(OrientDBGraphWrapper.scala:433)
	at org.apache.spark.orientdb.graphs.OrientDBEdgeRelation$$anonfun$schema$2.apply(OrientDBRelation.scala:163)
	at org.apache.spark.orientdb.graphs.OrientDBEdgeRelation$$anonfun$schema$2.apply(OrientDBRelation.scala:158)
	at scala.Option.getOrElse(Option.scala:121)

**Comment by sbcd90** [comment]
Unfortunately, only EmbeddedList, EmbeddedSet, EmbeddedMap, LinkList, LinkSet, LinkMap, LinkBag types are supported as of now.
I'll add support for Link.

**Comment by sbcd90** [comment]
hello @Dollyn , i have added support for `linktypes`. This issue should be fixed now.

**Comment by 237693991** [comment]
could you add linktypes support for spark 1.6

**Comment by 237693991** [comment]
@sbcd90   could you add linktypes support for spark 1.6 , thanks
