### ISSUE TITLE
Parse Datetime Error

### ISSUE THREAD

**Issue by DamianZhou** [orientechnologies/spark-orientdb#8]
## situation

Read from Orientdb by
```
import org.apache.spark.sql.SQLContext

val sqlContext = new SQLContext(sc)
val loadedDf = sqlContext.read
                   .format("org.apache.spark.orientdb.graphs")
                   .option("dburl", ORIENTDB_CONNECTION_URL)
                   .option("user", ORIENTDB_USER)
                   .option("password", ORIENTDB_PASSWORD)
                   .option("edgetype", test_edge_type2)
                   .load()
```
When there is no any DATETIME property，it works fine.

But when there is a DATETIME property, it returns 
```java
...
Exception in thread "main" java.text.ParseException: Unparseable date: "Sat Aug 12 12:50:12 CST 2017"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at org.apache.spark.orientdb.documents.Conversions$.orientDBDTtoSparkDT(Conversions.scala:79)
...
```
## possible solution

checkout `Conversions.scala:79`

I have tested in pure scala,
```
// it works fine
    import java.util.Locale

    var source = "Sat Aug 12 12:50:12 CST 2017"
    val dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss Z yyyy", Locale.ENGLISH)
    val testDate = dateFormat.parse(source)
    println(testDate.getTime().toString)

//it fails
    var source = "Sat Aug 12 12:50:12 CST 2017"
    val dateFormat = new SimpleDateFormat("E MMM dd HH:mm:ss Z yyyy")
    val testDate = dateFormat.parse(source)
    println(testDate.getTime().toString)
```

**Comment by sbcd90** [comment]
Hello @DamianZhou,

Thanks for pointing the issue & suggesting a possible solution.
The fix is available in the latest master branch. It will part of next release.
